<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-29 22:32
=======
# Generated by Django 3.0.7 on 2023-06-29 08:35
>>>>>>> 643c488e0d28c2906dddabdd0f9410468d70ba01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_juego_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']])),
                ('mensaje', models.TextField()),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], {1, 'reclamo'}, [2, 'sugerencia']])),
>>>>>>> 643c488e0d28c2906dddabdd0f9410468d70ba01
            ],
        ),
    ]
